name: Docker image update check
on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: alpine:latest
          image: mogzol/nordvpn-tinyproxy:latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.check.outputs.needs-updating == 'true'

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: mogzol/nordvpn-tinyproxy:latest
        if: steps.check.outputs.needs-updating == 'true'
